#statistical functions
#1-aggregate functions
#2-analytical functions

select sum(salary) from emp;#data point/measure
select max(salary) from emp;
select max(empid) from emp;
SELECT * FROM EMP WHERE SALARY=60000;
SELECT MIN(SALARY) FROM EMP;
SELECT * FROM EMP WHERE SALARY=10000;
SELECT COUNT(EMPID) FROM EMP;
SELECT COUNT(LOCATION) FROM EMP;
SELECT COUNT(DEPT) FROM EMP;
SELECT COUNT(DISTINCT DEPT) FROM EMP;
SELECT COUNT(DISTINCT GENDER)FROM EMP;
SELECT DISTINCT DEPT FROM EMP;
SELECT DISTINCT LOCATION FROM EMP;
SELECT AVG(SALARY)FROM EMP;#SUM/OBSERVATIONS
SELECT EMPID,ENAME,DEPT,SUM(SALARY) FROM EMP;
SELECT ENAME,UPPER(ENAME)FROM EMP;
SELECT * FROM EMP WHERE DEPT='SALES';
SELECT SUM(SALARY) FROM EMP WHERE DEPT='SALES';
SELECT SUM(SALARY) FROM EMP WHERE DEPT='IT';
SELECT SUM(SALARY) FROM EMP WHERE LOCATION='CHENNAI';
SELECT DEPT,SUM(SALARY) FROM EMP GROUP BY DEPT;
SELECT LOCATION,SUM(SALARY) FROM EMP group by LOCATION;

























